### ISSUE TITLE
HardwareProfile and HardwareDetails mutually exclusive?

### ISSUE THREAD

**Issue by honza** [metalkube/baremetal-operator#118]
Are HardwareProfile and HardwareDetails mutually exclusive?

**Comment by dhellmann** [comment]
No, they're not. The profile is intended to be a name of a well-known set of details. The details are what is really on the host. Eventually, when inspection is implemented, we will expand the details data structure to include values like the drive serial numbers and other values that would be unique to a given host.

**Comment by honza** [comment]
Thanks for the explanation!
