### ISSUE TITLE
segfault accessing Spec.UserData

### ISSUE THREAD

**Issue by mhrivnak** [metalkube/baremetal-operator#125]
When `UserData` is accessed [here](https://github.com/metalkube/baremetal-operator/blob/18cc1d5/pkg/controller/baremetalhost/baremetalhost_controller.go#L497), if it is not set, the process will segfault.

We need to check that `UserData != nil` before accessing it.

**Comment by russellb** [comment]
Fixed by https://github.com/metalkube/baremetal-operator/pull/138
