### ISSUE TITLE
document using minikube for development setup

### ISSUE THREAD

**Issue by dhellmann** [metalkube/baremetal-operator#24]
Our dev setup instructions focus on minishift, but should also include minikube. It's not hugely different, but we should make sure we have the difference clearly documented.

**Comment by hardys** [comment]
Note that dev-scripts should now provide a functional alternative on machines where you can run multiple VMs, ref https://github.com/metalkube/dev-scripts/pull/98 which shows interacting with a deployed cluster.

**Comment by dhellmann** [comment]
See #45
