### ISSUE TITLE
Utilize state from Ironic to determine if BMC credentials are valid

### ISSUE THREAD

**Issue by russellb** [metalkube/baremetal-operator#35]
So far a BareMetalHost will reflect an error if BMC credentials are not set.  Once those credentials are set in Ironic, we can use the state of the ironic node to determine if the BMC credentials are valid.  We know the credentials are valid when the bare metal node moves to the "manageable" state.

https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/node_states.html

**Comment by dhellmann** [comment]
#48 implemented this
